language:
- python
python:
- '3.4'
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- coverage run --source='.' manage.py test
after_success:
- coveralls
notifications:
  email:
    recipients:
      - s.elahmadie@gmail.com
    on_success: change
    on_failure: always