# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='accuracy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='attack_magic_potency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='attack_power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='bind_resist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='blind_resist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='blunt_resist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='crit_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='determination',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='dexterity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='earth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='fire',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='healing_magic_potency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='heavy_resist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='ice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='intelligence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='lightning',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='magic_defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='mind',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='mp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='parry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='piercing_resist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='piety',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='poison_resist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='silence_resist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='skill_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='slashing_resist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='sleep_resist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='slow_resist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='spell_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='stun_resist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='tp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='vitality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='water',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='wind',
            field=models.IntegerField(default=0),
        ),
    ]
