# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='lvl_alchemist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lvl_arcanist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lvl_archer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lvl_armorer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lvl_astrologian',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lvl_blacksmith',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lvl_botanist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lvl_carpenter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lvl_conjurer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lvl_culinarian',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lvl_dark_night',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lvl_fisher',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lvl_gladiator',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lvl_goldsmith',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lvl_lancer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lvl_leatherworker',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lvl_machinist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lvl_marauder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lvl_miner',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lvl_pugilist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lvl_rogue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lvl_thaumaturge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lvl_weaver',
            field=models.IntegerField(default=0),
        ),
    ]
